on: [push]
name: CI

jobs:
  test:
    name: Rust project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        channel:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
